#!/usr/bin/env node
// SPDX-FileCopyrightText: 2026 Numen Games S.L.
// SPDX-License-Identifier: MIT
/**
 * rule-index.mjs — the reading list AGENTS.md carries, generated from the rules.
 *
 * THE PROBLEM THIS SOLVES
 * -----------------------
 * `standards/`, `protocols/` and `canon/` hold 46 rule documents, 91k tokens
 * of them. An agent starting a task has no cheap way to know which ones apply:
 * it reads everything, or it guesses. AGENTS.md says the documents exist and
 * that each opens with a `**Binds:**` line, which is true and not actionable —
 * the agent still has to open 46 files to read 46 lines.
 *
 * So the lines come to it. One row per rule, its identifier, what it rules and
 * whom it binds, ~1k tokens for the set. The agent reads the table and opens
 * only what its task touches.
 *
 * WHY GENERATED AND NOT WRITTEN
 * -----------------------------
 * A hand-written index of 46 documents is D-031 again: it goes stale the first
 * time someone edits a `Binds:` line, and nothing notices, because nothing
 * reads it back. `[section].astro` already refuses to hand-write its indexes
 * for exactly this reason.
 *
 * The shape is `ruleset-export.mjs`'s, which solves the same problem for branch
 * protection — generate from the source of truth, and let `--check` exit 1 when
 * the written copy has drifted:
 *
 *   node machine/tools/rule-index.mjs            # rewrite the block in AGENTS.md
 *   node machine/tools/rule-index.mjs --check    # exit 1 if it has drifted
 *   node machine/tools/rule-index.mjs --print    # the block, to stdout
 *
 * WHAT IT QUOTES AND WHAT IT REFUSES TO INVENT
 * --------------------------------------------
 * The scope cell is the document's own `**Binds:**` line, shortened at a clause
 * boundary, never paraphrased. 15 of the 46 have no such line — the eight
 * `canon/` by design (STD-007 asks for it in standards/ and protocols/ only),
 * plus seven standards and one protocol. Those rows say `no scope line` rather
 * than carry a guess: a stated gap sends a reader to the document, an invented
 * scope sends them away from it.
 *
 * WHAT THIS TOOL DOES NOT CHECK (D-025 — declare your blindness):
 * see machine/scripts/blind-spots.json, entry "rule-index".
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { ROOT, parseFM } from '../scripts/lib/frontmatter.mjs';
import { declareBlindSpots } from '../scripts/lib/blindness.mjs';

export const BEGIN = '<!-- rule-index:begin — generated by machine/tools/rule-index.mjs; do not edit by hand -->';
export const END = '<!-- rule-index:end -->';

const TARGET = 'AGENTS.md';
const DIRS = ['standards', 'protocols', 'canon'];
const SCOPE_CHARS = 96;
const TITLE_CHARS = 46;

/** The `**Binds:**` line, joined across wrapped lines, or null when absent.
 *
 *  The line wraps: STD-007 caps it at 15 words but the file is hard-wrapped at
 *  80 columns, so `**Binds:**` on one line and its tail on the next is the
 *  normal shape. Reading to the next blank line — and stopping at any bold
 *  line that follows — is what keeps PRO-003 from
 *  ending at "the Oracle who opens, reviews" and STD-004 at "the directories
 *  `machine/scripts/lib/rules.json`", which reverses its meaning. */
function bindsOf(text) {
  const lines = text.split('\n');
  const at = lines.findIndex((l) => l.startsWith('**Binds:**'));
  if (at < 0) return null;
  const parts = [lines[at].slice('**Binds:**'.length)];
  for (let i = at + 1; i < lines.length; i++) {
    const l = lines[i];
    if (!l.trim() || l.startsWith('**') || l.startsWith('#')) break;
    parts.push(l);
  }
  const line = parts.join(' ').replace(/\s+/g, ' ').trim();
  return line.replace(/\.$/, '') || null;
}

/** Shortened at a clause boundary, never mid-word: the reader must be able to
 *  find these words in the document they came from. */
function shorten(s) {
  if (s.length <= SCOPE_CHARS) return s;
  const head = s.slice(0, SCOPE_CHARS);
  const at = Math.max(head.lastIndexOf(';'), head.lastIndexOf(' — '), head.lastIndexOf(', '));
  return `${(at > 40 ? head.slice(0, at) : head.slice(0, head.lastIndexOf(' '))).trim()}…`;
}

/** The title without its own identifier prefix — the table has an ID column.
 *  A few documents write a sentence where the register wants a name (CAN-008's
 *  runs to 86 characters); the cell is a label, so it is cut at a word. */
function cleanTitle(raw, id) {
  const t = String(raw ?? '').replace(new RegExp(`^${id}\\s*[—–-]\\s*`), '').trim();
  if (t.length <= TITLE_CHARS) return t;
  const head = t.slice(0, TITLE_CHARS);
  return `${head.slice(0, head.lastIndexOf(' ')).replace(/[,;:]$/, '')}…`;
}

/** Why a document carries no scope line.
 *
 *  14 of 46 have none, and 14 of those 14 are STD-007 working as written:
 *  the guard asks for `Binds:` in standards/ and protocols/ only, and skips
 *  `subtype: register` inside them — `if (!register && NEEDS_PLATES.has(dir))`.
 *
 *  A register is a lookup table: STD-015 lists the engineering practices,
 *  STD-026 the operative words. It governs nobody by itself; the standard pointing at it
 *  does. A canon says why things are as they are, and a reason binds everyone
 *  who leans on it.
 *
 *  So the cell names the exemption instead of repeating `no scope line`
 *  fourteen times. A reader who sees `register` knows to look for the standard
 *  that cites it; a bare gap would have sent them nowhere. Anything else is an
 *  omission, and `machine/guards/test/std-007-one-page.test.mjs` fails on it. */
function whyNoScope(file, fm) {
  if (fm.subtype === 'register') return 'register — scope belongs to the standard that cites it';
  if (file.startsWith('canon/')) return 'canon — states why, binds whoever leans on it';
  return 'no scope line';
}

/** The line under the table: what the gaps mean, in the corpus's own terms. */
function footnote(rows) {
  const n = (p) => rows.filter(p).length;
  const reg = n((r) => r.binds === null && r.cell.startsWith('register'));
  const can = n((r) => r.binds === null && r.cell.startsWith('canon'));
  const gap = n((r) => r.cell === 'no scope line');
  const parts = [`${rows.length} rule documents`];
  if (reg) parts.push(`${reg} are registers and ${can ? 'take' : 'takes'} their scope from the standard that cites them`);
  if (can) parts.push(`${can} are canon, which state why rather than whom`);
  parts.push(gap
    ? `${gap} declare no scope and no exemption covers ${gap === 1 ? 'it' : 'them'} — open ${gap === 1 ? 'it' : 'those'} when in doubt`
    : 'every other document names whom it binds');
  return `${parts.join('; ')}.`;
}

export function buildIndex(root = ROOT) {
  const files = execFileSync('git', ['-C', root, 'ls-files', ...DIRS.map((d) => `${d}/*.md`)], { encoding: 'utf8' })
    .split('\n').filter(Boolean);
  const rows = [];
  for (const file of files) {
    const text = readFileSync(path.join(root, file), 'utf8');
    const fm = parseFM(text) ?? {};
    const id = typeof fm.id === 'string' && fm.id ? fm.id : path.basename(file, '.md');
    const binds = bindsOf(text);
    rows.push({
      id,
      file,
      binds,
      title: cleanTitle(fm.title, id),
      cell: binds === null ? whyNoScope(file, fm) : shorten(binds),
    });
  }
  rows.sort((a, b) => a.id.localeCompare(b.id));
  const lines = [
    BEGIN,
    '',
    `| Rule | What it rules | Binds |`,
    '|---|---|---|',
    ...rows.map((r) => `| \`${r.id}\` | ${r.title} | ${r.cell} |`),
    '',
    footnote(rows),
    END,
  ];
  return { rows, block: lines.join('\n') };
}

/** AGENTS.md with the block replaced, or appended under its heading if absent. */
function splice(target, block) {
  const b = target.indexOf(BEGIN);
  const e = target.indexOf(END);
  if (b >= 0 && e > b) return target.slice(0, b) + block + target.slice(e + END.length);
  const heading = '## The rules that govern work here';
  const at = target.indexOf(heading);
  if (at < 0) {
    console.error(`rule-index: ${TARGET} has no "${heading}" section to hold the index`);
    process.exit(2);
  }
  const next = target.indexOf('\n## ', at + heading.length);
  const cut = next < 0 ? target.length : next;
  return `${target.slice(0, cut).replace(/\s+$/, '')}\n\n${block}\n${target.slice(cut)}`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  declareBlindSpots('rule-index');
  const argv = new Set(process.argv.slice(2));
  const file = path.join(ROOT, TARGET);
  const { block, rows } = buildIndex();

  if (argv.has('--print')) {
    console.log(block);
    process.exit(0);
  }

  const current = readFileSync(file, 'utf8');
  const wanted = splice(current, block);

  if (argv.has('--check')) {
    if (current === wanted) {
      console.log(`rule-index: ${TARGET} matches the corpus (${rows.length} rules).`);
      process.exit(0);
    }
    /* Name the rules that differ, not the diff: the reader wants to know which
       document was edited, and a table diff says nothing at a glance. */
    const have = new Map([...current.matchAll(/^\| `([A-Z]{3}-\d{3})` \| (.*) \|$/gm)].map((m) => [m[1], m[2]]));
    const want = new Map([...wanted.matchAll(/^\| `([A-Z]{3}-\d{3})` \| (.*) \|$/gm)].map((m) => [m[1], m[2]]));
    const ids = [...new Set([...have.keys(), ...want.keys()])].sort();
    const drift = ids.filter((id) => have.get(id) !== want.get(id));
    console.error(`rule-index: ${TARGET} has DRIFTED from the corpus — ${drift.length || 'the'} row(s) stale. The rules are right; the file is not.`);
    for (const id of drift) {
      if (!have.has(id)) console.error(`  ${id}  missing from ${TARGET}`);
      else if (!want.has(id)) console.error(`  ${id}  listed in ${TARGET}, not a rule document`);
      else console.error(`  ${id}\n      file  : ${have.get(id)}\n      corpus: ${want.get(id)}`);
    }
    console.error(`\nRegenerate it: node machine/tools/rule-index.mjs`);
    process.exit(1);
  }

  writeFileSync(file, wanted);
  console.log(`rule-index: ${TARGET} rewritten from the corpus — ${rows.length} rules, ${rows.filter((r) => r.binds === null).length} without a scope line.`);
}
