#!/usr/bin/env node
// SPDX-FileCopyrightText: 2026 Numen Games S.L.
// SPDX-License-Identifier: MIT
//
// entities — one walk over the entity cards, two outputs.
//
// An entity card (objects/<name>.md) is an index: an entity has forms (a
// model, a portrait, a sound, a sheet), every form has its own licence and
// rights holder, and every form has copies — where its bytes are, each with
// a sha256 and a size. The card never holds the bytes; the depot does. The
// card says what exists and where; this script says whether that is still
// true.
//
//   node scripts/entities.mjs          walks objects/, writes objects/catalogue.json
//                                      (what numinia.com reads — header data only,
//                                      never the body)
//   node scripts/entities.mjs --check  also fetches every copy of every form,
//                                      hashes the bytes, compares with the card,
//                                      reads the licence embedded in the file
//                                      where the format has a slot for one, and
//                                      writes objects/CHECK.md dated and signed
//                                      with the commit. Exit 1 on any mismatch
//                                      or unreachable copy.
//
// The check is run BY HAND and its report is committed: CI never fetches a
// third-party host, so a host being down does not turn main red, and the
// committed report says on which day, at which commit, the copies were seen.
// Resilience is the count in that report, never a badge.
//
// Runs from any tree that has an objects/ folder (the tests use a scratch
// clone). Copies may be `url:` (http, https, file) or `path:` + `commit:`
// inside a repository; a path copy is read from git at that commit.

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { declareBlindSpots } from './lib/blindness.mjs';
import { parseYamlFrontmatter } from './lib/entity-card.mjs';

declareBlindSpots('entities');

const ROOT = process.cwd();
const DIR = path.join(ROOT, 'objects');
const CHECK = process.argv.includes('--check');

if (!existsSync(DIR)) {
  console.error(`entities: no objects/ folder under ${ROOT}`);
  process.exit(2);
}

/* ---------- the walk ---------- */

const cards = readdirSync(DIR).filter((f) => f.endsWith('.md') && f !== 'CHECK.md' && f !== 'README.md').sort();
const entities = [];
const problems = [];

for (const file of cards) {
  const rel = `objects/${file}`;
  const text = readFileSync(path.join(DIR, file), 'utf8');
  const fm = parseYamlFrontmatter(text);
  if (!fm) { problems.push(`${rel}: no frontmatter`); continue; }
  const slug = file.replace(/\.md$/, '');
  const forms = Array.isArray(fm.forms) ? fm.forms : [];
  entities.push({
    slug,
    path: rel,
    id: fm.id,
    title: fm.title,
    entity: fm.entity,
    status: fm.status,
    version: fm.version,
    license: fm.license,
    created: fm.created,
    updated: fm.updated,
    related: fm.related ?? [],
    forms: forms.map((f) => ({
      role: f.role,
      format: f.format,
      version: f.version,
      license: f.license,
      rights_holder: f.rights_holder,
      embedded_license: f.embedded_license,
      copies: (Array.isArray(f.copies) ? f.copies : []).map((c) => ({
        ...(c.url ? { url: c.url } : {}),
        ...(c.path ? { path: c.path } : {}),
        ...(c.commit ? { commit: c.commit } : {}),
        ...(c.repo ? { repo: c.repo } : {}),
        sha256: c.sha256,
        bytes: c.bytes,
        ...(c.note ? { note: c.note } : {}),
      })),
    })),
  });
}

if (problems.length) {
  for (const p of problems) console.error(`entities: ${p}`);
  process.exit(1);
}

const catalogue = {
  $comment: 'Generated by scripts/entities.mjs from objects/*.md — do not edit. The cards are the source; this is the index numinia.com reads. Bytes live in the copies, never here. Undated on purpose: it is a pure function of the cards, so the same cards give the same file at any commit; the dated artefact is CHECK.md.',
  entities,
};
writeFileSync(path.join(DIR, 'catalogue.json'), `${JSON.stringify(catalogue, null, 2)}\n`);
console.log(`entities: ${entities.length} card(s), ${entities.reduce((n, e) => n + e.forms.length, 0)} form(s), ${entities.reduce((n, e) => n + e.forms.reduce((m, f) => m + f.copies.length, 0), 0)} cop(y/ies) → objects/catalogue.json`);

if (!CHECK) process.exit(0);

/* ---------- the check ---------- */

const rows = [];
for (const e of entities) {
  for (const f of e.forms) {
    for (const c of f.copies) {
      const where = c.url ?? `${c.repo ?? 'this repository'}:${c.path}@${c.commit}`;
      let verdict, detail = '';
      try {
        const bytes = await fetchCopy(c);
        const sha = createHash('sha256').update(bytes).digest('hex');
        if (sha !== c.sha256) { verdict = 'mismatch'; detail = `got ${sha.slice(0, 12)}…`; }
        else if (bytes.length !== c.bytes) { verdict = 'mismatch'; detail = `size ${bytes.length}, card says ${c.bytes}`; }
        else {
          verdict = 'ok';
          const emb = embeddedLicence(bytes, f.format);
          if (emb !== null) {
            const declared = String(f.embedded_license ?? '').toLowerCase();
            const found = emb.toLowerCase();
            detail = `embedded: ${emb}`;
            if (declared && declared !== 'none' && !found.includes(declared.replace(/-1\.0$/, '').toLowerCase()))
              { verdict = 'mismatch'; detail = `embedded licence "${emb}", card says "${f.embedded_license}"`; }
          }
        }
      } catch (err) {
        verdict = 'unreachable'; detail = String(err.message ?? err).split('\n')[0].slice(0, 80);
      }
      rows.push({ slug: e.slug, role: f.role, where, verdict, detail });
    }
  }
}

const count = { ok: 0, mismatch: 0, unreachable: 0 };
for (const r of rows) count[r.verdict]++;
const today = new Date().toISOString().slice(0, 10);
const commit = gitShort();

const md = [
  '---',
  'id: "objects-check"',
  `title: "Copy check — ${today}"`,
  'type: meta',
  'status: active',
  'version: "0.1.0"',
  `created: "${new Date().toISOString().replace(/\\.\\d{3}Z$/, 'Z')}"`,
  `updated: "${new Date().toISOString().replace(/\\.\\d{3}Z$/, 'Z')}"`,
  'license: "CC0-1.0"',
  'author: "scripts/entities.mjs"',
  'provenance: ai-generated',
  '---',
  '',
  `# Copy check — ${today} at ${commit}`,
  '',
  'Written by `node scripts/entities.mjs --check`, run by hand and committed with its date.',
  'One row per copy of every form of every card in `objects/`. `ok` = the bytes were',
  'fetched and their SHA-256 and size match the card. Where the format carries a',
  'licence inside the file (VRM meta, glTF extras), it is read and compared with the',
  'card\'s `embedded_license`. CI never runs this: a third-party host being down is',
  'not a defect of the archive, and the archive does not depend on it.',
  '',
  `**${count.ok} ok · ${count.mismatch} mismatch · ${count.unreachable} unreachable** over ${rows.length} cop${rows.length === 1 ? 'y' : 'ies'}.`,
  '',
  '| card | form | copy | verdict | detail |',
  '|---|---|---|---|---|',
  ...rows.map((r) => `| ${r.slug} | ${r.role} | ${shorten(r.where)} | ${r.verdict} | ${r.detail} |`),
  '',
].join('\n');
writeFileSync(path.join(DIR, 'CHECK.md'), md);
console.log(`entities: ${count.ok} ok · ${count.mismatch} mismatch · ${count.unreachable} unreachable → objects/CHECK.md`);
process.exit(count.mismatch + count.unreachable > 0 ? 1 : 0);

/* ---------- helpers ---------- */

function gitShort() {
  try { return execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim(); }
  catch { return 'no-git'; }
}

async function fetchCopy(c) {
  if (c.url) {
    if (c.url.startsWith('file://')) return readFileSync(fileURLToPath(c.url));
    const res = await fetch(c.url, { redirect: 'follow' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return Buffer.from(await res.arrayBuffer());
  }
  if (c.path && c.commit) {
    if (c.repo) throw new Error('a path copy in another repository needs a url — use the raw url pinned to the commit');
    return execFileSync('git', ['show', `${c.commit}:${c.path}`], { cwd: ROOT, maxBuffer: 1 << 28 });
  }
  throw new Error('a copy is a url, or a path pinned to a commit');
}

/** The licence a file declares INSIDE itself, or null when the format has no
 *  slot this reader knows. glTF-binary (GLB, VRM): the JSON chunk's
 *  `extensions.VRM.meta.licenseName` (VRM 0.x), `VRMC_vrm.meta.licenseUrl`
 *  (VRM 1.0) or `asset.extras.license` / `extras.license` (plain glTF). */
function embeddedLicence(bytes, format) {
  const fmt = String(format ?? '').toLowerCase();
  if (!['glb', 'vrm', 'gltf-binary'].includes(fmt)) return null;
  try {
    if (bytes.readUInt32LE(0) !== 0x46546c67) return 'none (not a GLB container)';
    const chunkLen = bytes.readUInt32LE(12);
    const json = JSON.parse(bytes.subarray(20, 20 + chunkLen).toString('utf8'));
    const v0 = json.extensions?.VRM?.meta;
    if (v0) return [v0.licenseName, v0.author].filter(Boolean).join(' by ') || 'none';
    const v1 = json.extensions?.VRMC_vrm?.meta;
    if (v1) return [v1.licenseUrl, ...(v1.authors ?? [])].filter(Boolean).join(' by ') || 'none';
    const extra = json.asset?.extras?.license ?? json.extras?.license;
    return extra ? String(extra) : 'none';
  } catch { return 'none (unreadable)'; }
}

function shorten(s) {
  if (s.length <= 72) return s;
  return `${s.slice(0, 40)}…${s.slice(-28)}`;
}
