// SPDX-FileCopyrightText: 2026 Numen Games S.L.
// SPDX-License-Identifier: MIT
//
// Raw-markdown static endpoint. Two kinds of page are served here, and the
// difference is the whole point.
//
//   A DOCUMENT is a file. Its .md is read off disk, frontmatter included:
//   the page is a rendering, the file is the document, and what you download
//   is byte-for-byte what the repository holds.
//
//   A COMPOSED PAGE has no file. The home, /scheme, the six function pages
//   and the section indexes are built from the registers (STD-027, STD-001,
//   the corpus). Their markdown is GENERATED by @/lib/composed-md from the
//   same modules the pages themselves read — the same query, answered in
//   markdown — and it says so in its own preamble, so nobody cites a view as
//   if it were a record.
//
// One route because they share an address space: /canon/can-001.md is a
// document, /canon.md is the index of the folder that holds it. Two catch-all
// routes over one pattern would be resolved by luck.
import fs from "node:fs";
import type { APIRoute } from "astro";
import { getPublicCorpus } from "@/lib/corpus";
import { allComposedPages } from "@/lib/composed-md";

export async function getStaticPaths() {
  const documents = (await getPublicCorpus()).map((entry) => ({
    params: { slug: entry.id },
    props: { filePath: entry.filePath as string, body: null },
  }));

  // "" (the home) has no route segment of its own; /.md is not an address,
  // so it is served at /home.md.
  const composed = (await allComposedPages()).map((page) => ({
    params: { slug: page.route === "" ? "home" : page.route.replace(/^\//, "") },
    props: { filePath: null, body: page.body },
  }));

  // A composed page whose address is already a document's would shadow it.
  // Both lists are derived from registers that move, so this is checked
  // rather than asserted by reading them.
  const taken = new Set(documents.map((d) => d.params.slug));
  const clash = composed.filter((c) => taken.has(c.params.slug));
  if (clash.length) {
    throw new Error(
      `Composed markdown collides with a document address: ` +
        `${clash.map((c) => `/${c.params.slug}.md`).join(", ")}. ` +
        `A view must not be downloadable at the address of a record.`,
    );
  }

  return [...documents, ...composed];
}

export const GET: APIRoute = ({ props }) => {
  const raw =
    props.filePath !== null
      ? fs.readFileSync(props.filePath as string, "utf-8")
      : (props.body as string);
  return new Response(raw, {
    headers: { "Content-Type": "text/markdown; charset=utf-8" },
  });
};
