// SPDX-FileCopyrightText: 2026 Numen Games S.L.
// SPDX-License-Identifier: MIT
// @ts-check
import path from "node:path";
import { fileURLToPath } from "node:url";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import tailwindcss from "@tailwindcss/vite";
import pagefind from "astro-pagefind";
import { defineConfig } from "astro/config";
import rehypeContextCard from "./src/lib/rehype-context-card.mjs";
import rehypeBindsState from "./src/lib/rehype-binds-state.mjs";
import { rehypeShiftHeadings } from "./src/lib/rehype-shift-headings.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// https://astro.build/config
export default defineConfig({
	site: "https://numinia.org",
	output: "static",
	// Load the next page while the pointer rests on its link, so a click lands
	// on a page already in memory (2026-09-28).
	prefetch: { prefetchAll: true, defaultStrategy: "hover" },
	// /misiones merged into /missions (MIS-066); old URLs keep resolving.
	// MIS-109 phase B: the six seminal canon documents took C-NNN filenames,
	// and Astro derives /corpus/<id> from the filename — so every published
	// canon URL changed. These keep the old ones resolving, same as MIS-066.
	// DEUDA-404 records a page of 890.4 KB generated by a change discarded
	// before push (72bff4c): the URL never went live, and the entry is about
	// page weight, not a broken link. See DBT-004.
	redirects: {
		// Every rule here is a promise that a retired address still leads to the
		// document answering the question it answered (STD-028 URL-005). Nothing
		// else belongs in this block.
		//
		// 2026-09-20 (ADR-047): this block held 574 rules. 373 led to an index,
		// the debt register or a report saying a batch of documents was deleted, which
		// answers nothing — those addresses now meet the site's own 404, which offers
		// navigation. 40 were Spanish paths duplicating an English one, 0 differed
		// from the live address only by the retired `/corpus/` prefix, and 35 ended at
		// a page this build does not publish. Every survivor was restriped to the new
		// shape — a document is served at /<series>/<id> (URL-001) — and every chain
		// was resolved to its end, so no reader takes two hops.
		//
		// Before adding a rule, answer URL-005 out loud: does the target document
		// answer what the dead address answered? If the question was withdrawn, add
		// nothing — deleting the address is the honest act, and
		// machine/scripts/check-url-shape.mjs rejects a redirect into an index.
		// → legal
		"/legal/privacidad": "/legal/privacy",
		"/legal/privacidad.md": "/legal/privacy.md",
		"/legal/terminos": "/legal/terms",
		"/legal/terminos.md": "/legal/terms.md",
		// → the Veil is its English name (2026-09-29): BLU-011 renamed
		"/blueprints/book-and-velo": "/blueprints/book-and-veil",
		"/blueprints/book-and-velo.md": "/blueprints/book-and-veil.md",
		// → the design kit
		// → / — the classification is the home (2026-09-21). /archive asked
		// "how is this organised?"; the root now answers it. Its children keep
		// their addresses (/archive/<function>).
		"/archive": "/",
		// → /system/… — eight site pages filed in the System drawer (2026-09-21).
		// They stood at the root with no link from anywhere; same page, new
		// address, and a door from /system/.
		"/cao": "/system/cao",
		"/continuity": "/system/continuity",
		"/gaps": "/system/gaps",
		"/language": "/system/language",
		"/sales": "/system/sales",
		"/simulations": "/system/simulations",
		"/solutions": "/system/solutions",
		"/wardley": "/system/wardley",
		// → /system/sys-006 — BLU-008 reshelved as a reference manual (2026-09-21)
		"/blueprints/nwos-system": "/system/sys-006-nwos-system",
		"/blueprints/nwos-system.md": "/system/sys-006-nwos-system.md",
		// → /archive — the fondo pages became function pages
		"/archive/agents": "/archive/agency",
		"/archive/blueprints": "/blueprints",
		"/archive/canon": "/canon",
		"/archive/operations": "/archive/administration",
		"/archive/protocols": "/procedures",
		// → canon
		"/canon/2026_04_15-epistemic_relations_between_numen_games_and_numina-v020": "/canon/can-006-epistemic-relations",
		"/canon/2026_04_15-pragmatic_numen_system-v020": "/canon/can-007-pragmatic-numen-system",
		"/canon/c-001-welcome-to-numinia": "/canon/can-001-welcome-to-numinia",
		"/canon/c-002-brand-and-culture": "/canon/can-002-brand-and-culture",
		"/canon/c-003-attributes-and-ranks": "/canon/can-004-role-structure",
		"/canon/c-004-role-structure": "/canon/can-004-role-structure",
		"/canon/c-005-licensing": "/canon/can-005-licensing",
		"/canon/c-007-rank-specifications": "/canon/can-004-role-structure",
		"/canon/compendium-of-attributes-and-ranks-in-numinia": "/canon/can-004-role-structure",
		// ADR-057 (2026-09-24): CAN-004 absorbed CAN-003. The address survives and points at the heir (URL-005).
		"/canon/can-003-attributes-and-ranks": "/canon/can-004-role-structure",
		"/canon/numinia-brand-and-culture": "/canon/can-002-brand-and-culture",
		"/canon/rank-specifications": "/canon/can-004-role-structure",
		"/canon/role-structure-in-the-numinia-system": "/canon/can-004-role-structure",
		"/canon/welcome-to-numinia": "/canon/can-001-welcome-to-numinia",
		"/guilds/alquimistas/gld-001-charter": "/canon/can-004-role-structure",
		"/guilds/alquimistas/gld-005-roster": "/canon/can-004-role-structure",
		"/guilds/centinelas/gld-004-charter": "/canon/can-004-role-structure",
		"/guilds/centinelas/gld-006-roster": "/canon/can-004-role-structure",
		"/guilds/exegetas/gld-002-charter": "/canon/can-004-role-structure",
		"/guilds/exegetas/gld-007-roster": "/canon/can-004-role-structure",
		"/guilds/procuradores/gld-003-charter": "/canon/can-004-role-structure",
		"/guilds/procuradores/gld-008-roster": "/canon/can-004-role-structure",
		"/standards/2026_04_14-analogous_terminology_numina-v020": "/canon/can-004-role-structure",
		// → standards
		"/decisions/adr-001": "/standards/std-006-plain-text-is-sovereign",
		"/decisions/adr-002": "/standards/std-006-plain-text-is-sovereign",
		"/decisions/adr-003": "/standards/std-006-plain-text-is-sovereign",
		"/decisions/adr-004": "/standards/std-018-one-document-one-identifier",
		"/decisions/adr-005": "/standards/std-001-the-series",
		"/decisions/adr-023": "/standards/std-007-one-page-per-document",
		"/decisions/adr-024": "/standards/std-007-one-page-per-document",
		"/decisions/adr-026": "/standards/std-010-licensing",
		"/decisions/adr-027": "/standards/std-004-the-header",
		"/decisions/adr-028": "/standards/std-004-the-header",
		"/decisions/adr-029": "/standards/std-004-the-header",
		"/decisions/adr-031": "/standards/std-010-licensing",
		"/decisions/adr-035": "/standards/std-024-a-series-is-a-function",
		"/decisions/adr-037": "/standards/std-015-engineering-checks",
		"/decisions/adr-038": "/standards/std-009-which-rule-wins",
		"/decisions/adr-039": "/standards/std-010-licensing",
		"/decisions/adr-040": "/standards/std-025-a-mission-is-a-card",
		"/decisions/dec-001": "/standards/std-006-plain-text-is-sovereign",
		"/governance": "/standards/std-009-which-rule-wins",
		"/missions/template": "/standards/std-001-the-series",
		"/missions/template-changes": "/standards/std-001-the-series",
		"/missions/template-example": "/standards/std-001-the-series",
		"/protocols/2026_04_14-read_me_how_to_archive-v020": "/standards/std-024-a-series-is-a-function",
		"/protocols/p-010-how-to-archive": "/standards/std-024-a-series-is-a-function",
		"/protocols/pro-010-how-to-archive": "/standards/std-024-a-series-is-a-function",
		"/standards/2026_08_18-sistema_de_diseno-v510": "/design",
		"/diseno": "/design",
		"/standards/engineering-standards": "/standards/std-005-when-a-rule-bites",
		"/standards/governance": "/standards/std-009-which-rule-wins",
		"/standards/s-001-glossary": "/standards/std-001-the-series",
		"/standards/s-003-platform-role-system": "/standards/std-003-platform-ranks",
		"/standards/s-004-header-standard": "/standards/std-004-the-header",
		"/standards/std-001-glossary": "/standards/std-001-the-series",
		"/standards/std-002-governance": "/standards/std-009-which-rule-wins",
		"/standards/std-011-external-standards": "/standards/std-005-when-a-rule-bites",
		"/standards/std-003-platform-role-system": "/standards/std-003-platform-ranks",
		"/standards/std-004-header-standard": "/standards/std-004-the-header",
		"/standards/std-005-engineering-standards": "/standards/std-005-when-a-rule-bites",
		"/standards/std-006-archive-substance": "/standards/std-006-plain-text-is-sovereign",
		"/standards/std-007-plain-writing": "/standards/std-007-one-page-per-document",
		"/standards/std-008-design-system": "/standards/std-008-design-tokens",
		"/standards/std-009-core-rules": "/standards/std-009-which-rule-wins",
		"/system/sys-004-document-relations": "/standards/std-009-which-rule-wins",
		// → procedures (the series was protocols/ until 2026-10-03, ADR-067 cut 2)
		"/protocols/approval-request-template": "/procedures/pro-008-decision",
		"/protocols/p-001-agent-briefing": "/procedures/pro-001-agent-session",
		"/protocols/p-002-onboarding-agente-v1": "/procedures/pro-001-agent-session",
		"/protocols/p-003-ciclo-mision-v1": "/procedures/pro-003-mission-cycle",
		"/protocols/p-004-inter-agent-v1": "/procedures/pro-003-mission-cycle",
		"/protocols/p-005-escalation-v1": "/procedures/pro-005-escalation",
		"/protocols/p-006-session-close-v1": "/procedures/pro-001-agent-session",
		"/protocols/pro-015-joining-and-leaving": "/procedures/pro-015-joining",
		"/protocols/p-007-context-load-v1": "/procedures/pro-001-agent-session",
		"/protocols/p-008-approval-brief-v1": "/procedures/pro-008-decision",
		"/protocols/p-009-mission-briefing": "/procedures/pro-003-mission-cycle",
		"/protocols/p-011-security-audit": "/procedures/pro-011-security-audit",
		"/protocols/p-012-ruling-with-a-condition": "/procedures/pro-008-decision",
		"/protocols/p-013-handing-a-guard-to-ci": "/procedures/pro-013-handing-a-guard-to-ci",
		// → procedures — the series took the industry's word (ADR-067 cut 2, 2026-10-03):
		// protocols/ became procedures/, every PRO-NNN kept its identifier. One rule per
		// document and one per .md view, plus the index.
		"/protocols": "/procedures",
		"/protocols/pro-001-agent-session": "/procedures/pro-001-agent-session",
		"/protocols/pro-001-agent-session.md": "/procedures/pro-001-agent-session.md",
		"/protocols/pro-003-mission-cycle": "/procedures/pro-003-mission-cycle",
		"/protocols/pro-003-mission-cycle.md": "/procedures/pro-003-mission-cycle.md",
		"/protocols/pro-005-escalation": "/procedures/pro-005-escalation",
		"/protocols/pro-005-escalation.md": "/procedures/pro-005-escalation.md",
		"/protocols/pro-008-decision": "/procedures/pro-008-decision",
		"/protocols/pro-008-decision.md": "/procedures/pro-008-decision.md",
		"/protocols/pro-011-security-audit": "/procedures/pro-011-security-audit",
		"/protocols/pro-011-security-audit.md": "/procedures/pro-011-security-audit.md",
		"/protocols/pro-013-handing-a-guard-to-ci": "/procedures/pro-013-handing-a-guard-to-ci",
		"/protocols/pro-013-handing-a-guard-to-ci.md": "/procedures/pro-013-handing-a-guard-to-ci.md",
		"/protocols/pro-014-producing-a-design-piece": "/procedures/pro-014-producing-a-design-piece",
		"/protocols/pro-014-producing-a-design-piece.md": "/procedures/pro-014-producing-a-design-piece.md",
		"/protocols/pro-015-joining": "/procedures/pro-015-joining",
		"/protocols/pro-015-joining.md": "/procedures/pro-015-joining.md",
		"/protocols/pro-016-applying-the-engineering-standard": "/procedures/pro-016-applying-the-engineering-standard",
		"/protocols/pro-016-applying-the-engineering-standard.md": "/procedures/pro-016-applying-the-engineering-standard.md",
		"/protocols/pro-017-rolling-up-the-week": "/procedures/pro-017-rolling-up-the-week",
		"/protocols/pro-017-rolling-up-the-week.md": "/procedures/pro-017-rolling-up-the-week.md",
		"/protocols/pro-018-publishing-a-repository": "/procedures/pro-018-publishing-a-repository",
		"/protocols/pro-018-publishing-a-repository.md": "/procedures/pro-018-publishing-a-repository.md",
		"/protocols/pro-019-holding-a-ritual": "/procedures/pro-019-holding-a-ritual",
		"/protocols/pro-019-holding-a-ritual.md": "/procedures/pro-019-holding-a-ritual.md",
		"/protocols/pro-020-putting-something-on-sale": "/procedures/pro-020-putting-something-on-sale",
		"/protocols/pro-020-putting-something-on-sale.md": "/procedures/pro-020-putting-something-on-sale.md",
		"/protocols/pro-021-closing-the-month": "/procedures/pro-021-closing-the-month",
		"/protocols/pro-021-closing-the-month.md": "/procedures/pro-021-closing-the-month.md",
		"/protocols/pro-022-building-the-living-pieces": "/procedures/pro-022-building-the-living-pieces",
		"/protocols/pro-022-building-the-living-pieces.md": "/procedures/pro-022-building-the-living-pieces.md",
		"/protocols/pro-023-bringing-a-rule-into-force": "/procedures/pro-023-bringing-a-rule-into-force",
		"/protocols/pro-023-bringing-a-rule-into-force.md": "/procedures/pro-023-bringing-a-rule-into-force.md",
		"/protocols/pro-024-leaving": "/procedures/pro-024-leaving",
		"/protocols/pro-024-leaving.md": "/procedures/pro-024-leaving.md",
		"/protocols/pro-025-handling-a-personal-data-breach": "/procedures/pro-025-handling-a-personal-data-breach",
		"/protocols/pro-025-handling-a-personal-data-breach.md": "/procedures/pro-025-handling-a-personal-data-breach.md",
		"/protocols/pro-026-answering-a-request-about-personal-data": "/procedures/pro-026-answering-a-request-about-personal-data",
		"/protocols/pro-026-answering-a-request-about-personal-data.md": "/procedures/pro-026-answering-a-request-about-personal-data.md",
		"/protocols/pro-027-changing-what-a-site-stores": "/procedures/pro-027-changing-what-a-site-stores",
		"/protocols/pro-027-changing-what-a-site-stores.md": "/procedures/pro-027-changing-what-a-site-stores.md",
		"/protocols/pro-028-qualifying-an-opportunity": "/procedures/pro-028-qualifying-an-opportunity",
		"/protocols/pro-028-qualifying-an-opportunity.md": "/procedures/pro-028-qualifying-an-opportunity.md",
		"/protocols/pro-029-making-a-proposal": "/procedures/pro-029-making-a-proposal",
		"/protocols/pro-029-making-a-proposal.md": "/procedures/pro-029-making-a-proposal.md",
		"/protocols/pro-030-closing-a-sale": "/procedures/pro-030-closing-a-sale",
		"/protocols/pro-030-closing-a-sale.md": "/procedures/pro-030-closing-a-sale.md",
		"/protocols/pro-031-bidding-for-a-tender": "/procedures/pro-031-bidding-for-a-tender",
		"/protocols/pro-031-bidding-for-a-tender.md": "/procedures/pro-031-bidding-for-a-tender.md",
		"/protocols/pro-032-applying-for-a-grant": "/procedures/pro-032-applying-for-a-grant",
		"/protocols/pro-032-applying-for-a-grant.md": "/procedures/pro-032-applying-for-a-grant.md",
		"/protocols/pro-033-screening-a-tender": "/procedures/pro-033-screening-a-tender",
		"/protocols/pro-033-screening-a-tender.md": "/procedures/pro-033-screening-a-tender.md",
		"/protocols/pro-034-auditing-a-sites-code": "/procedures/pro-034-auditing-a-sites-code",
		"/protocols/pro-034-auditing-a-sites-code.md": "/procedures/pro-034-auditing-a-sites-code.md",
		"/protocols/pro-035-watching-for-opportunities": "/procedures/pro-035-watching-for-opportunities",
		"/protocols/pro-035-watching-for-opportunities.md": "/procedures/pro-035-watching-for-opportunities.md",
		// → standards — STD-033 renamed when the account left for STD-036 (2026-09-26)
		"/standards/std-016-header-fields": "/standards/std-004-the-header",
		"/standards/std-016-header-fields.md": "/standards/std-004-the-header.md",
		"/standards/std-013-licence-allowlist-and-fields": "/standards/std-010-licensing",
		"/standards/std-013-licence-allowlist-and-fields.md": "/standards/std-010-licensing.md",
		"/standards/std-033-charges-and-the-account": "/standards/std-033-every-charge-delivers-something",
		"/standards/std-033-charges-and-the-account.md": "/standards/std-033-every-charge-delivers-something.md",
		// STD-005 renamed to its question; STD-032 reshelved as SYS-009, a map not a rule (2026-09-26)
		"/standards/std-005-engineering-baseline": "/standards/std-005-when-a-rule-bites",
		"/standards/std-005-engineering-baseline.md": "/standards/std-005-when-a-rule-bites.md",
		"/standards/std-032-the-design-system": "/system/sys-009-the-design-system",
		"/standards/std-032-the-design-system.md": "/system/sys-009-the-design-system.md",
		// → blueprints — BLU-016 renamed from its old subject to its question (2026-09-26)
		"/blueprints/outside-standards-under-consideration": "/blueprints/one-question-per-standard",
		"/blueprints/outside-standards-under-consideration.md": "/blueprints/one-question-per-standard.md",
		// → system
		"/blueprints/agent-experience": "/system/sys-002-agent-cycle",
		"/blueprints/archive-fondos": "/system/sys-003-archive-fondos",
		"/blueprints/cao-architecture": "/system/sys-001-cao-architecture",
		"/canon/archive-lore": "/system/sys-003-archive-fondos",
		// → operations
		"/operations/credential-map": "/operations/ops-009-secrets-handling",
		"/operations/legal/o-003-privacy-policy-numengames": "/legal/leg-001-privacy-policy-numengames",
		"/operations/legal/o-004-terms-and-conditions-numengames": "/legal/leg-002-terms-and-conditions-numengames",
		"/operations/legal/ops-003-privacy-policy-numengames": "/legal/leg-001-privacy-policy-numengames",
		"/operations/legal/ops-004-terms-and-conditions-numengames": "/legal/leg-002-terms-and-conditions-numengames",
		// → legal — the three legal texts leave operations/ for their own series (2026-09-27)
		"/operations/ops-003-privacy-policy-numengames": "/legal/leg-001-privacy-policy-numengames",
		"/operations/ops-003-privacy-policy-numengames.md": "/legal/leg-001-privacy-policy-numengames.md",
		"/operations/ops-004-terms-and-conditions-numengames": "/legal/leg-002-terms-and-conditions-numengames",
		"/operations/ops-004-terms-and-conditions-numengames.md": "/legal/leg-002-terms-and-conditions-numengames.md",
		"/operations/ops-010-cookie-policy-numengames": "/legal/leg-003-cookie-policy-numengames",
		"/operations/ops-010-cookie-policy-numengames.md": "/legal/leg-003-cookie-policy-numengames.md",
		"/operations/o-001-continuity": "/operations/ops-001-continuity",
		"/operations/o-002-contradictions": "/operations/ops-002-contradictions",
		"/operations/o-005-simulations": "/operations/ops-005-simulations",
		"/operations/o-006-solutions": "/operations/ops-006-solutions",
		"/operations/o-008-session-state": "/operations/ops-008-session-state",
		"/operations/security-policy": "/operations/ops-009-secrets-handling",
		"/operations/strategy/o-007-sales": "/operations/ops-007-sales",
		"/operations/strategy/ops-007-sales": "/operations/ops-007-sales",
		// → one pipeline (2026-10-02): grants left funding/ for opportunities/
		// as kind grant; the stages of a sale and of a grant became the stages
		// of an opportunity; the two cards became one. Records of calls the
		// house cannot win (GRA-2026-005/006, OPP-2026-005…019) were deleted,
		// not redirected: their question was withdrawn (URL-005).
		"/funding": "/opportunities/",
		"/funding/gra-2026-001": "/opportunities/opp-2026-021",
		"/funding/gra-2026-001.md": "/opportunities/opp-2026-021.md",
		"/funding/gra-2026-002": "/opportunities/opp-2026-022",
		"/funding/gra-2026-002.md": "/opportunities/opp-2026-022.md",
		"/funding/gra-2026-003": "/opportunities/opp-2026-023",
		"/funding/gra-2026-003.md": "/opportunities/opp-2026-023.md",
		"/funding/gra-2026-004": "/opportunities/opp-2026-024",
		"/funding/gra-2026-004.md": "/opportunities/opp-2026-024.md",
		"/standards/std-038-the-stages-of-a-sale": "/standards/std-038-the-stages-of-an-opportunity",
		"/standards/std-038-the-stages-of-a-sale.md": "/standards/std-038-the-stages-of-an-opportunity.md",
		"/standards/std-045-the-stages-of-a-grant": "/standards/std-038-the-stages-of-an-opportunity",
		"/standards/std-045-the-stages-of-a-grant.md": "/standards/std-038-the-stages-of-an-opportunity.md",
		"/standards/std-046-a-grant-has-a-record": "/standards/std-039-an-opportunity-has-a-record",
		"/standards/std-046-a-grant-has-a-record.md": "/standards/std-039-an-opportunity-has-a-record.md",
		"/operations/ops-018-the-house-card-for-tenders": "/operations/ops-018-the-house-card",
		"/operations/ops-018-the-house-card-for-tenders.md": "/operations/ops-018-the-house-card.md",
		"/operations/ops-019-the-house-card-for-grants": "/operations/ops-018-the-house-card",
		"/operations/ops-019-the-house-card-for-grants.md": "/operations/ops-018-the-house-card.md",
		// → decisions
		"/blueprints/mission-system": "/decisions/adr-041",
		"/blueprints/mission-system-v2": "/decisions/adr-041",
		"/canon/about-session-zero": "/decisions/adr-036",
		"/canon/c-006-session-zero": "/decisions/adr-036",
		"/canon/index": "/decisions/adr-036",
		"/canon/readme": "/decisions/adr-036",
		"/decisions/adr-032": "/decisions/adr-030",
		"/decisions/adr-033": "/decisions/adr-030",
		"/history/2026_04_07-epistemic_relations-v100": "/decisions/adr-041",
		"/history/2026_04_07-mission_system_v2-v100": "/decisions/adr-041",
		"/history/2026_09_07-brand_research_interview-v100": "/decisions/adr-041",
		"/history/2026_09_07-cultural_cartography-v100": "/decisions/adr-041",
		"/history/2026_09_07-financial_projections-v100": "/decisions/adr-041",
		"/history/2026_09_07-role_structure_treatise-v100": "/decisions/adr-041",
		"/history/2026_09_08-superseded_constitution-v200": "/decisions/adr-041",
		"/standards/standards": "/decisions/adr-041",
		// → reports
		"/blueprints/wardley-map": "/reports/rpt-003-wardley-map",
		// "/gaps" → the report used to sit here too, unreachable: a built page at
		// /gaps shadowed it. The page moved to /system/gaps (2026-09-21) and the
		// rule above sends the old address there — same page, not the report.
		"/reports/rpt-2026-04-07-gaps-capability-map": "/reports/rpt-008-gaps-capability-map",
		"/reports/rpt-2026-04-07-wardley-map": "/reports/rpt-003-wardley-map",
		// → lore — adventures split into tabletop/ and virtual-worlds/ (2026-09-24)
		"/lore/adventures/el-espejo-roto": "/lore/adventures/tabletop/el-espejo-roto",
		"/lore/adventures/session-zero": "/lore/adventures/virtual-worlds/session-zero",
		// → /brand — the old brand deck was merged into canon and records, and the
		// brand and culture book reads them (2026-10-03). Same question answered.
		"/lore/world/brand-and-culture": "/brand",
	},
	// MIS-088's /print/* intermediates are gone (2026-08-31). They existed
	// only as Chromium print targets for a PDF step the build never ran, so
	// they were served in production as a public half-feature. Removing the
	// pages removes the reason for the sitemap filter that hid them: there
	// is nothing left to exclude. See debt/D-035.
	integrations: [react(), sitemap(), pagefind()],
	// Every corpus document opens with a Summary/Epistemic/Pragmatic/Audience
	// blockquote. Markdown renders those four lines as one paragraph, which
	// reads as a grey wall. rehypeContextCard turns that one blockquote shape
	// into a definition list — one field per row — and leaves every other
	// blockquote untouched. See src/lib/rehype-context-card.mjs.
	markdown: {
		// Order matters: the card is built from the document's opening
		// blockquote, then every heading drops one level so the page keeps the
		// single h1 it printed itself. See rehype-shift-headings.mjs.
		rehypePlugins: [rehypeContextCard, rehypeBindsState, rehypeShiftHeadings],
	},
	vite: {
		// Tailwind 4 is a Vite plugin: the @astrojs/tailwind integration was
		// retired upstream and never accepted Astro 6+. The theme now lives in
		// src/styles/global.css (@theme), not in a tailwind.config file.
		plugins: [tailwindcss()],
		resolve: {
			alias: {
				"@": path.resolve(__dirname, "./src"),
			},
		},
	},
});
